language: node_js
node_js:
  - "9"
  - "10"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
